### PR TITLE
add 2048 game

### PR DESCRIPTION
**Pull request by 383494**

### CODE REVIEW

**Comment by MaxXSoft** [comment]
Awesome work! Thanks for contributing!

There's some bugs in your implementation, for example, when the board is:

```
__ __ __ __ 
__ __ __ __ 
4  2  4  __ 
16 8  2  4  
```

at this point I can not move left, but if I still type `a`, the game will freeze.

**Comment by 383494** [comment]
> Awesome work! Thanks for contributing!
> 
> There's some bugs in your implementation, for example, when the board is:
> 
> ```
> __ __ __ __ 
> __ __ __ __ 
> 4  2  4  __ 
> 16 8  2  4  
> ```
> 
> at this point I can not move left, but if I still type `a`, the game will freeze.

it did not freeze; it was just waiting 

> Awesome work! Thanks for contributing!
> 
> There's some bugs in your implementation, for example, when the board is:
> 
> ```
> __ __ __ __ 
> __ __ __ __ 
> 4  2  4  __ 
> 16 8  2  4  
> ```
> 
> at this point I can not move left, but if I still type `a`, the game will freeze.

it was waiting for another movement command.

**Comment by 383494** [comment]
> Awesome work! Thanks for contributing!
> 
> There's some bugs in your implementation, for example, when the board is:
> 
> ```
> __ __ __ __ 
> __ __ __ __ 
> 4  2  4  __ 
> 16 8  2  4  
> ```
> 
> at this point I can not move left, but if I still type `a`, the game will freeze.

it was waiting for another movement command.

**Comment by 383494** [comment]
fixed

**Comment by MaxXSoft** [comment]
LGTM. Thank you!

**Pull request merged**
